ERRO_TIPO_NAO_NUMERICO = "Esse tipo nao pode ser utilizado em expressoes numericas > "
ERRO_TIPOS_INCOMPATIVEIS = "Os tipos utilizados sao incompativeis > "
VARIAVEL_FUNCAO_NAO_DECLARADA = "A variavel ou funcao nao foi declarada > "
VARIAVEL_FUNCAO_JA_DECLARADA = "A variavel ou funcao ja foi declarada > " 
FUNCAO_SEM_RETORNO = "A funcao nao tem tipo de retorno mas esta tentando retornar um valor > "